# remember to use this compose file __ONLY__ for development/testing purposes
postgres:
    image: postgres:9.6
    environment:
        - POSTGRES_PASSWORD=$TEST_POSTGRES_PASSWORD
        - POSTGRES_USER=$TEST_POSTGRES_USER
        - POSTGRES_DB=$TEST_POSTGRES_DB
    ports:
        - "127.0.0.1:${TEST_POSTGRES_PORT}:5432"
