# Common variables, containers, jobs and steps.
job_defaults: &job_defaults
  working_directory: /app
  shell: /bin/bash --login

ruby_containers: &ruby_containers
  - &container-1_9
    image: datadog/docker-library:ddtrace_rb_1_9_3
    environment:
      - BUNDLE_GEMFILE=/app/Gemfile
  - &container-2_0
    image: datadog/docker-library:ddtrace_rb_2_0_0
    environment:
      - BUNDLE_GEMFILE=/app/Gemfile
  - &container-2_1
    image: datadog/docker-library:ddtrace_rb_2_1_10
    environment:
      - BUNDLE_GEMFILE=/app/Gemfile
  - &container-2_2
    image: datadog/docker-library:ddtrace_rb_2_2_10
    environment:
      - BUNDLE_GEMFILE=/app/Gemfile
  - &container-2_3
    image: datadog/docker-library:ddtrace_rb_2_3_7
    environment:
      - BUNDLE_GEMFILE=/app/Gemfile
  - &container-2_4
    image: datadog/docker-library:ddtrace_rb_2_4_4
    environment:
      - BUNDLE_GEMFILE=/app/Gemfile

test_containers: &test_containers
  - &container_postgres
    image: postgres:9.6
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
  - &container_mysql
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=mysql
      - MYSQL_USER=mysql
  - &container_elasticsearch
    image: elasticsearch:2.4
  - &container_redis
    image: redis:3.0
  - &container_mongo
    image: mongo:3.5
  - &container_memcached
    image: memcached:1.5-alpine
  - &container_agent
    image: datadog/docker-dd-agent
    environment:
      - DD_APM_ENABLED=true
      - DD_BIND_HOST=0.0.0.0
      - DD_API_KEY=invalid_key_but_this_is_fine

step_init_bundle_checksum: &step_init_bundle_checksum
  run:
    name: Initialize bundle cache key
    command: |
      touch .circleci/bundle_checksum
step_bundle_install: &step_bundle_install
  run:
    name: Install gem dependencies
    command: bundle install
step_rubocop: &step_rubocop
  run:
    name: Delint with Rubocop
    command: echo bundle exec rake rubocop
step_appraisal_install: &step_appraisal_install
  run:
    name: Install Appraisal gems
    command: bundle exec appraisal install
step_compute_bundle_checksum: &step_compute_bundle_checksum
  run:
    name: Compute bundle checksum
    command: |
      cat Gemfile.lock gemfiles/*.gemfile.lock > .circleci/bundle_checksum
step_run_all_tests: &step_run_all_tests
  run:
    name: Run tests
    command: bundle exec rake ci
step_release_docs: &step_release_docs
  run:
    name: Upload release docs
    command: S3_DIR=trace bundle exec rake release:docs

filters_all_branches_and_tags: &filters_all_branches_and_tags
  filters:
    tags:
      only: /.*/
filters_only_release_tags: &filters_only_release_tags
  filters:
    branches:
      ignore: /.*/
    tags:
      only: /^v\d+(\.\d+){0,3}(\.(alpha|beta|rc)\d+)?$/

aliases:
  - &bundler_cache
      key: 'betav7-bundle-{{ .Environment.CIRCLE_JOB }}-{{ checksum "Gemfile" }}-{{ checksum "ddtrace.gemspec" }}-{{ checksum "Appraisals" }}'
      paths:
        - vendor/bundle
        - gemfiles/
        - Gemfile.lock
  - &bundler_init bundle --path vendor/bundle
  - &build_files
      root: .
      paths:
        - vendor/bundle
        - gemfiles/
        - Gemfile.lock
  - &wait_for_postgres
      name: Waiting for Postgres to be ready
      command: |
        for i in `seq 1 30`;
        do
          nc -z localhost 5432 && echo Success && exit 0
          echo -n .
          sleep 1
        done
        echo Failed waiting for Postgres && exit 1

#linting_job: &linting_job
#  <<: *job_defaults
#  steps:
#    - checkout
#    - attach_workspace:
#        at: /app
#    - run: *bundler_init
#    - *step_rubocop


version: 2.0
jobs:
  bundler-2.3:
    <<: *job_defaults
    docker:
      - <<: *container-2_3
        environment:
          - TEST_DATADOG_INTEGRATION: 1
    steps:
      - checkout
      - restore_cache: *bundler_cache
      - run: *bundler_init
      - *step_bundle_install
      - *step_appraisal_install
      - save_cache: *bundler_cache
      - persist_to_workspace:
          <<: *bundler_cache
          root: .
  benchmark-2.3-instrumented-1: &b23i
    <<: *job_defaults
    docker:
      - <<: *container-2_3
        environment:
          - TEST_DATADOG_INTEGRATION: 1
      - *container_postgres
      - *container_redis
      - *container_agent
    parallelism: 3
    steps:
      - checkout
      - attach_workspace:
          at: /app
      - run: *bundler_init
      - run: *wait_for_postgres
      - run:
          name: Run Benchmark
          command: bundle exec appraisal rails5-postgres-sidekiq ruby benchmarks/sidekiq_test.rb 2>&1 1>/dev/null | tee benchmark-instrumented-$CIRCLE_BUILD_NUM-$CIRCLE_NODE_INDEX.csv
      - persist_to_workspace:
          root: .
          paths:
            - '*.csv'
  benchmark-2.3-not-instrumented-1: &b23ni
    <<: *job_defaults
    docker:
      - <<: *container-2_3
        environment:
          - TEST_DATADOG_INTEGRATION: 1
      - *container_postgres
      - *container_redis
      - *container_agent
    parallelism: 3
    steps:
      - checkout
      - attach_workspace:
          at: /app
      - run: *bundler_init
      - run: *wait_for_postgres
      - run:
          name: Run Benchmark without ddtracer
          command: "rm -f lib/ddtrace.rb && bundle exec appraisal rails5-postgres-sidekiq ruby benchmarks/sidekiq_test.rb 2>&1 1>/dev/null | tee benchmark-not-instrumented-$CIRCLE_BUILD_NUM-$CIRCLE_NODE_INDEX.csv"
      - persist_to_workspace:
          root: .
          paths:
            - '*.csv'
  benchmark-2.3-instrumented-1: *b23i
  benchmark-2.3-instrumented-2: *b23i
  benchmark-2.3-instrumented-3: *b23i
  benchmark-2.3-instrumented-4: *b23i
  benchmark-2.3-instrumented-5: *b23i
  benchmark-2.3-instrumented-6: *b23i
  benchmark-2.3-instrumented-7: *b23i
  benchmark-2.3-instrumented-8: *b23i
  benchmark-2.3-instrumented-9: *b23i
  benchmark-2.3-instrumented-10: *b23i
  benchmark-2.3-instrumented-11: *b23i
  benchmark-2.3-instrumented-12: *b23i
  benchmark-2.3-instrumented-13: *b23i
  benchmark-2.3-instrumented-14: *b23i
  benchmark-2.3-instrumented-15: *b23i
  benchmark-2.3-instrumented-16: *b23i
  benchmark-2.3-instrumented-17: *b23i
  benchmark-2.3-instrumented-18: *b23i
  benchmark-2.3-instrumented-19: *b23i
  benchmark-2.3-instrumented-20: *b23i
  benchmark-2.3-not-instrumented-2: *b23ni
  benchmark-2.3-not-instrumented-3: *b23ni
  benchmark-2.3-not-instrumented-4: *b23ni
  benchmark-2.3-not-instrumented-5: *b23ni
  benchmark-2.3-not-instrumented-6: *b23ni
  benchmark-2.3-not-instrumented-7: *b23ni
  benchmark-2.3-not-instrumented-8: *b23ni
  benchmark-2.3-not-instrumented-9: *b23ni
  benchmark-2.3-not-instrumented-10: *b23ni
  benchmark-2.3-not-instrumented-11: *b23ni
  benchmark-2.3-not-instrumented-12: *b23ni
  benchmark-2.3-not-instrumented-13: *b23ni
  benchmark-2.3-not-instrumented-14: *b23ni
  benchmark-2.3-not-instrumented-15: *b23ni
  benchmark-2.3-not-instrumented-16: *b23ni
  benchmark-2.3-not-instrumented-17: *b23ni
  benchmark-2.3-not-instrumented-18: *b23ni
  benchmark-2.3-not-instrumented-19: *b23ni
  benchmark-2.3-not-instrumented-20: *b23ni


  benchmark-2.3-aggregate:
    <<: *job_defaults
    docker:
      - <<: *container-2_3
        environment:
          - TEST_DATADOG_INTEGRATION: 1
    steps:
      - checkout
      - run: *bundler_init
      - attach_workspace:
          at: /app
      - run: *bundler_init
      - run:
          command: |
            ls -la
            mkdir -p /tmp/csvs
            cp *.csv /tmp/csvs
      - store_artifacts:
          path: /tmp/csvs
      - run: bundle exec ruby benchmarks/process_results.rb *.csv

  test-2.3:
    <<: *job_defaults
    docker:
      - <<: *container-2_3
        environment:
          - TEST_DATADOG_INTEGRATION: 1
      - *container_postgres
      - *container_mysql
      - *container_elasticsearch
      - *container_redis
      - *container_mongo
      - *container_memcached
      - *container_agent
    steps:
      - checkout
      - restore_cache: *bundler_cache
      - run: *bundler_init
      - *step_bundle_install
      - *step_appraisal_install
      - save_cache: *bundler_cache
      - run: *bundler_init
      - *step_run_all_tests

  deploy-release:
    <<: *job_defaults
    docker:
      - *container-2_4
    steps:
      - checkout
      - run:
          command: |
            apt-get -y -qq update
            apt-get -y -qq install awscli
      - *step_bundle_install
      - *step_release_docs

workflows:
  version: 2
  build-and-test:
    jobs:
#      - checkout-2.0:
#          <<: *filters_all_branches_and_tags
#      - build-2.0:
#          <<: *filters_all_branches_and_tags
#          requires:
#            - checkout-2.0
#      - test-2.0:
#          <<: *filters_all_branches_and_tags
#          requires:
#            - build-2.0
#      - checkout-2.1:
#          <<: *filters_all_branches_and_tags
#      - build-2.1:
#          <<: *filters_all_branches_and_tags
#          requires:
#            - checkout-2.1
#      - test-2.1:
#          <<: *filters_all_branches_and_tags
#          requires:
#            - build-2.1
#      - checkout-2.2:
#          <<: *filters_all_branches_and_tags
#      - build-2.2:
#          <<: *filters_all_branches_and_tags
#          requires:
#            - checkout-2.2
#      - test-2.2:
#          <<: *filters_all_branches_and_tags
#          requires:
#            - build-2.2
      - bundler-2.3: *filters_all_branches_and_tags
      - benchmark-2.3-not-instrumented-1: &wb23ni
          <<: *filters_all_branches_and_tags
          requires:
            - bundler-2.3
      - benchmark-2.3-not-instrumented-2: *wb23ni
      - benchmark-2.3-not-instrumented-3: *wb23ni
      - benchmark-2.3-not-instrumented-4: *wb23ni
      - benchmark-2.3-not-instrumented-5: *wb23ni
      - benchmark-2.3-not-instrumented-6: *wb23ni
      - benchmark-2.3-not-instrumented-7: *wb23ni
      - benchmark-2.3-not-instrumented-8: *wb23ni
      - benchmark-2.3-not-instrumented-9: *wb23ni
      - benchmark-2.3-not-instrumented-10: *wb23ni
      - benchmark-2.3-not-instrumented-11: *wb23ni
      - benchmark-2.3-not-instrumented-12: *wb23ni
      - benchmark-2.3-not-instrumented-13: *wb23ni
      - benchmark-2.3-not-instrumented-14: *wb23ni
      - benchmark-2.3-not-instrumented-15: *wb23ni
      - benchmark-2.3-not-instrumented-16: *wb23ni
      - benchmark-2.3-not-instrumented-17: *wb23ni
      - benchmark-2.3-not-instrumented-18: *wb23ni
      - benchmark-2.3-not-instrumented-19: *wb23ni
      - benchmark-2.3-not-instrumented-20: *wb23ni
      - benchmark-2.3-instrumented-1: &wb23i
          <<: *filters_all_branches_and_tags
          requires:
            - bundler-2.3
      - benchmark-2.3-instrumented-2: *wb23i
      - benchmark-2.3-instrumented-3: *wb23i
      - benchmark-2.3-instrumented-4: *wb23i
      - benchmark-2.3-instrumented-5: *wb23i
      - benchmark-2.3-instrumented-6: *wb23i
      - benchmark-2.3-instrumented-7: *wb23i
      - benchmark-2.3-instrumented-8: *wb23i
      - benchmark-2.3-instrumented-9: *wb23i
      - benchmark-2.3-instrumented-10: *wb23i
      - benchmark-2.3-instrumented-11: *wb23i
      - benchmark-2.3-instrumented-12: *wb23i
      - benchmark-2.3-instrumented-13: *wb23i
      - benchmark-2.3-instrumented-14: *wb23i
      - benchmark-2.3-instrumented-15: *wb23i
      - benchmark-2.3-instrumented-16: *wb23i
      - benchmark-2.3-instrumented-17: *wb23i
      - benchmark-2.3-instrumented-18: *wb23i
      - benchmark-2.3-instrumented-19: *wb23i
      - benchmark-2.3-instrumented-20: *wb23i
      - benchmark-2.3-aggregate:
          <<: *filters_all_branches_and_tags
          requires:
            - benchmark-2.3-not-instrumented-1
            - benchmark-2.3-not-instrumented-2
            - benchmark-2.3-not-instrumented-3
            - benchmark-2.3-not-instrumented-4
            - benchmark-2.3-not-instrumented-5
            - benchmark-2.3-not-instrumented-6
            - benchmark-2.3-not-instrumented-7
            - benchmark-2.3-not-instrumented-8
            - benchmark-2.3-not-instrumented-9
            - benchmark-2.3-not-instrumented-10
            - benchmark-2.3-not-instrumented-11
            - benchmark-2.3-not-instrumented-12
            - benchmark-2.3-not-instrumented-13
            - benchmark-2.3-not-instrumented-14
            - benchmark-2.3-not-instrumented-15
            - benchmark-2.3-not-instrumented-16
            - benchmark-2.3-not-instrumented-17
            - benchmark-2.3-not-instrumented-18
            - benchmark-2.3-not-instrumented-19
            - benchmark-2.3-not-instrumented-20
            - benchmark-2.3-instrumented-1
            - benchmark-2.3-instrumented-2
            - benchmark-2.3-instrumented-3
            - benchmark-2.3-instrumented-4
            - benchmark-2.3-instrumented-5
            - benchmark-2.3-instrumented-6
            - benchmark-2.3-instrumented-7
            - benchmark-2.3-instrumented-8
            - benchmark-2.3-instrumented-9
            - benchmark-2.3-instrumented-10
            - benchmark-2.3-instrumented-11
            - benchmark-2.3-instrumented-12
            - benchmark-2.3-instrumented-13
            - benchmark-2.3-instrumented-14
            - benchmark-2.3-instrumented-15
            - benchmark-2.3-instrumented-16
            - benchmark-2.3-instrumented-17
            - benchmark-2.3-instrumented-18
            - benchmark-2.3-instrumented-19
            - benchmark-2.3-instrumented-20


#      - test-2.3:
#          <<: *filters_all_branches_and_tags
#      - deploy-release:
#          <<: *filters_only_release_tags
#          requires:
#            - test-1.9
#            - test-2.0
#            - test-2.1
#            - test-2.2
#            - test-2.3
#            - test-2.4
